### ISSUE TITLE
Improve typing

### ISSUE THREAD

**Issue by guscardvs** [Neoteroi/rodi#24]
https://github.com/Neoteroi/rodi/blob/a8cc027cfe8d30a8622d4c39e9af847a9ffa09d6/rodi/__init__.py#L207

Is it possible to improve typing on GetServicesContext by adding generics to the provider param on init?

**Comment by RobertoPrevato** [comment]
Hi! Yes, I think so. Just to clarify, in which way would you like to use Generics here?

Annotations here should look _something_ like this - I don´t see any easy way to use generics on the context class:

```python
 def __init__(self, provider : Services | None = None, scoped_services: dict[Type[T], T] | None = None):
```

**Comment by guscardvs** [comment]
Yes, i think i meant something like this :sweat_smile: , is it ok to send a pull request with this change?
